### ISSUE TITLE
trace-define-pass should use current-error-port

### ISSUE THREAD

**Issue by amirouche** [nanopass/nanopass-framework-scheme#24]
As of right now `trace-define-pass` output the trace in stdout, it should use stderr.

**Comment by akeep** [comment]
``trace-define-pass`` just uses ``trace-let``, so it prints out wherever your host system's trace output goes (where the host system is Chez Scheme, Ikarus, or Vicare in this case).

**Comment by amirouche** [comment]
Thanks
