### ISSUE TITLE
Could nanopass-framework-scheme be published on AKKU?

### ISSUE THREAD

**Issue by ufo5260987423** [nanopass/nanopass-framework-scheme#29]
Hi, I'm implementing a Language Protocol Server named [scheme-langserver](https://github.com/ufo5260987423/scheme-langserver/pulls) and adding some type inference features. It would be convenient if this repository was published on Akku. 
[Akku.scm](https://akkuscm.org/) is a language package manager for Scheme. It grabs hold of code and vigorously shakes it until it behaves properly.

**Comment by weinholt** [comment]
Nanopass is actually already available in Akku: https://akkuscm.org/packages/nanopass/
